
services:
  postgres:
    image: postgres:15
    container_name: postgres_song_library
    ports:
      - "5430:5432"
    volumes:
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./.docker-volumes/idx_pg_data:/var/lib/postgresql/data
    env_file:
      - .envs/.env
